AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    sam-app

    Sample SAM Template for sam-app


Globals:
  Function:
    Timeout: 3


Resources:

  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.hello
      Runtime: python3.6
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
      Policies:
        - AWSCloudMapDiscoverInstanceAccess

  WorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.world
      Runtime: python3.6
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /world
            Method: get
      Policies:
        - AWSCloudMapDiscoverInstanceAccess

  ExampleStream:
    Type: AWS::Kinesis::Stream
    Properties:
      ShardCount: 1

  ExampleNameSpace:
    Type: AWS::ServiceDiscovery::HttpNamespace
    Properties:
      Name: sls.willy.works

  ExampleService:
    Type: AWS::ServiceDiscovery::Service
    Properties:
      Name: example-stream
      NamespaceId: !Ref ExampleNameSpace

  ExampleInstance:
    Type: AWS::ServiceDiscovery::Instance
    Properties:
      InstanceAttributes:
        env: prod
      InstanceId: !Ref ExampleStream
      ServiceId: !Ref ExampleService

Outputs:

  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
